version: "3.9"

services:
    HostA:
        build: router
        image: firewall-lab-image
        container_name: hostA
        networks:
            net-192.168.60.0:
                ipv4_address: 192.168.60.2
        tty: true
        cap_add:
                - ALL    
    HostB:
        build: router
        image: firewall-lab-image
        container_name: hostB
        networks:
            net-192.168.60.0:
                ipv4_address: 192.168.60.3
        tty: true
        cap_add:
                - ALL    
    Router:  
        build: router
        image: firewall-lab-image
        container_name: router
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.11
            net-192.168.60.0:
                ipv4_address: 192.168.60.11
networks:
    net-192.168.60.0:
        driver_opts:
            com.docker.network.bridge.enable_ip_masquerade: "false"
        driver: macvlan
        name: net-192.168.60.0
        internal: true
        ipam:
            config:
                - subnet: 192.168.60.0/24
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
